/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef SecurityFunction
#define SecurityFunction
#ifdef __cplusplus
extern "C" {
#endif


//获取应用签名
jstring getAppSign(JNIEnv*);

//获取未md5加密应用签名
const char* getAppUnEncryptSign(JNIEnv*);

void exitApplication(JNIEnv*);

void isAppSignCorrect(JNIEnv*);

void isAppTraced(JNIEnv*);

#ifdef __cplusplus
}

#endif
#endif
